In [427]:
import numpy as np 

In [428]:
str_length = int(input())
str = np.zeros(str_length, dtype=int)
for i in range(str_length):
    str[i] = int(input())
str

ValueError: invalid literal for int() with base 10: ''

In [ ]:
frame_number = 3
#frame = np.zeros(frame_number, dtype=int)
frame = np.array([-1, -1, -1])

In [ ]:
def find_optimal_replace_index(current_index,str,frame):
    if -1 in frame:
        return np.where(frame == -1)[0][0]
    
    farthest_index = -1
    most_distance = 0
    for i in range(len(frame)):
        
        for j in range(current_index+1,len(str)):
            if frame[i]==str[j]:
                break
            #if problem remove below comment
            #j+=1
            if j>most_distance:
                most_distance=j
                farthest_index=i
    return farthest_index

In [ ]:

hit_count = 0
miss_count = 0
current_index = 0
for page in str:
    if page in frame:
        hit_count+=1
        current_index+=1
        continue
    
    miss_count+=1
    replace_index = find_optimal_replace_index(current_index, str, frame)
    frame[replace_index] = page
    current_index+=1

[ 7 -1 -1]
[ 7  0 -1]
[7 0 1]
17
4
13
[2 0 1]
[2 0 1]
8
6
13
[2 0 3]
[2 0 3]
8
10
9
[2 4 3]
[2 4 3]
[2 4 3]
12
11
[2 0 3]
[2 0 3]
[2 0 3]
14
15
[2 0 1]
[2 0 1]
[2 0 1]
[2 0 1]
18
19
[7 0 1]
[7 0 1]
[7 0 1]


In [ ]:
if -1 in frame:
    print(np.where(frame == -1)[0][0])

In [ ]:
print(hit_count)
print(miss_count)

11
9
