In [3]:
import numpy as np  

In [4]:
block_number=int(input("Enter the number of memory blocks: "))
block_size=np.zeros(block_number,dtype=int)

for i in range(block_number):
    block_size[i]=int(input("Enter the size of block "+str(i+1)+": "))


In [5]:
block_size

array([ 50,  75, 150, 175, 300])

In [7]:
process_number=int(input("Enter the number of processes: "))
process_size=np.zeros(process_number,dtype=int)

for i in range(process_number):
    process_size[i]=int(input("Enter the size of process "+str(i+1)+": "))

In [ ]:
process_size

array([80])

In [12]:
#input for block status
free_block = np.zeros(block_number,dtype=bool)
for i in range(block_number):
    free_block[i] = bool(int(input("Enter 1 if block "+str(i+1)+"is free, 0 if block "+str(i+1)+"is allocated: ")))
free_block

array([False,  True, False,  True, False])

In [10]:

allocated_process = np.zeros(process_number,dtype=bool)

allocation_map = [["process","allocated block"]]

for i in range(process_number):
    target_block = -1
    for j in range(block_number):
        
        if block_size[j]>=process_size[i] and  free_block[j]:
            if(target_block==-1):
                target_block = j
            elif(block_size[target_block]>=block_size[j]):
                target_block = j
            
    if(target_block!=-1):
        allocated_process[i] = True
        allocation_map.append(["process:"+str(i+1),"block:"+str(target_block+1)])
        block_size[target_block] -= process_size[i]
        if block_size[target_block]==0:
                free_block[target_block]=False
        
    if(allocated_process[i] == False):
        allocation_map.append(["process:"+str(i+1),"not allocated"])

In [11]:
allocation_map

[['process', 'allocated block'],
 ['process:1', 'block:2'],
 ['process:2', 'block:2'],
 ['process:3', 'block:4'],
 ['process:4', 'block:4']]

In [ ]:
block_size

array([100,   0,  83,  75, 100])