In [1]:
import numpy as np  

In [2]:
block_number=int(input("Enter the number of memory blocks: "))
block_size=np.zeros(block_number,dtype=int)

for i in range(block_number):
    block_size[i]=int(input("Enter the size of block "+str(i+1)+": "))


ValueError: invalid literal for int() with base 10: ''

In [ ]:
block_size

array([100,  80,  83,  75, 100])

In [ ]:
process_number=int(input("Enter the number of processes: "))
process_size=np.zeros(process_number,dtype=int)

for i in range(process_number):
    process_size[i]=int(input("Enter the size of process "+str(i+1)+": "))

In [ ]:
process_size

array([80])

In [ ]:
#input for block status
free_block = np.zeros(block_number,dtype=bool)
for i in range(block_number):
    free_block[i] = bool(input("Enter 1 if block "+str(i+1)+"is free, 0 if block "+str(i+1)+"is allocated: "))

In [ ]:

allocated_process = np.zeros(process_number,dtype=bool)

allocation_map = [["process","allocated block"]]

for i in range(process_number):
    target_block = -1
    for j in range(block_number):
        
        if block_size[j]>=process_size[i] and  free_block[j]:
            if(target_block==-1):
                target_block = j
            elif(block_size[target_block]<=block_size[j]):
                target_block = j
            
    if(target_block!=-1):
        allocated_process[i] = True
        allocation_map.append(["process:"+str(i+1),"block:"+str(target_block+1)])
        block_size[target_block] -= process_size[i]
        if block_size[target_block]==0:
                free_block[target_block]=False
        
    if(allocated_process[i] == False):
        allocation_map.append(["process:"+str(i+1),"not allocated"])

In [ ]:
allocation_map

[['process', 'allocated block'], ['process:1', 'block:2']]

In [ ]:
block_size

array([100,   0,  83,  75, 100])